FROM rust:slim AS build
WORKDIR /build
COPY backend backend
COPY Cargo.lock .
COPY Cargo.toml .
RUN cargo build --release --package backend

FROM debian:bookworm-slim AS release
COPY --from=build /build/target/release/backend /bin/backend
ENV PH_STORAGE_LOCATION="/var/data"
VOLUME [ "/var/data" ]
EXPOSE 80
ENTRYPOINT [ "/bin/backend" ]